package com.ebike.marketplaceModule.advisor;

public enum AdvisorIntent {
    GREETING, VEHICLE_SEARCH, VEHICLE_RECOMMENDATION, VEHICLE_DETAIL, VEHICLE_COMPARE,
    VEHICLE_PRICE, VEHICLE_BRAND, AVAILABLE_VEHICLE_BRANDS, VEHICLE_CATEGORY,
    VEHICLE_CONDITION, VEHICLE_MILEAGE, VEHICLE_YEAR, VEHICLE_LOCATION, VEHICLE_FUEL,
    VEHICLE_TRANSMISSION, VEHICLE_SEATS, VEHICLE_COLOR, VEHICLE_FEATURES, VEHICLE_HISTORY,
    BUY_VEHICLE, SELL_VEHICLE, EXCHANGE_VEHICLE, VEHICLE_VALUATION, FINANCE, FAVORITE,
    ACCOUNT, LISTING, CONTACT_SELLER, APPOINTMENT, WEBSITE_GUIDE, POLICY, SECURITY,
    SCAM_WARNING, GENERAL_VEHICLE_KNOWLEDGE, FOLLOW_UP, UNKNOWN;

    public String apiName() { return name().toLowerCase(java.util.Locale.ROOT); }
}
