import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, Headphones, RefreshCw, Search, ShieldAlert, UserRoundCheck } from "lucide-react";
import { supportAPI } from "@ebike/shared-code/api";
import type { SupportTicket, SupportTicketPriority, SupportTicketStatus } from "@ebike/shared-code/types";
import { useLocation } from "react-router-dom";

const statusNames: Record<SupportTicketStatus,string>={OPEN:"Mới tiếp nhận",IN_PROGRESS:"Đang xử lý",WAITING_CUSTOMER:"Chờ khách hàng",RESOLVED:"Đã giải quyết",CLOSED:"Đã đóng"};
const priorityNames: Record<SupportTicketPriority,string>={LOW:"Thấp",NORMAL:"Bình thường",HIGH:"Cao",URGENT:"Khẩn cấp"};
const statuses=Object.keys(statusNames) as SupportTicketStatus[]; const priorities=Object.keys(priorityNames) as SupportTicketPriority[];
const SupportConsolePage=()=>{
 const scope: "admin"|"manager"=useLocation().pathname.startsWith("/manager")?"manager":"admin";
 const [items,setItems]=useState<SupportTicket[]>([]),[selected,setSelected]=useState<SupportTicket|null>(null),[search,setSearch]=useState(""),[filter,setFilter]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const load=async()=>{try{setLoading(true);const data=await supportAPI.adminList(scope,{status:filter||undefined,search:search||undefined});setItems(data);setSelected(old=>data.find(x=>x.id===old?.id)??data[0]??null);setError("");}catch(e){setError(e instanceof Error?e.message:"Không thể tải yêu cầu hỗ trợ.");}finally{setLoading(false);}};
 useEffect(()=>{void load();},[filter]);
 const stats=useMemo(()=>({open:items.filter(x=>x.status==="OPEN").length,doing:items.filter(x=>x.status==="IN_PROGRESS").length,urgent:items.filter(x=>x.priority==="URGENT").length,done:items.filter(x=>x.status==="RESOLVED"||x.status==="CLOSED").length}),[items]);
 const save=async(patch:{status?:SupportTicketStatus;priority?:SupportTicketPriority;staffNote?:string;assignedTo?:string})=>{if(!selected)return;try{setSaving(true);const next=await supportAPI.update(scope,selected.id,patch);setSelected(next);setItems(v=>v.map(x=>x.id===next.id?next:x));setError("");}catch(e){setError(e instanceof Error?e.message:"Không thể cập nhật yêu cầu.");}finally{setSaving(false);}};
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Customer care center</p><h1 className="mt-2 text-3xl font-bold">Trung tâm hỗ trợ</h1><p className="mt-1 text-sm text-slate-500">Tiếp nhận, phân công và theo dõi toàn bộ yêu cầu khách hàng.</p></div><button onClick={()=>void load()} className="flex items-center gap-2 rounded-lg border bg-white px-4 py-2 text-sm font-semibold"><RefreshCw size={16}/>Làm mới</button></div>
 {error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Mới tiếp nhận",stats.open,Headphones],["Đang xử lý",stats.doing,Clock3],["Khẩn cấp",stats.urgent,ShieldAlert],["Hoàn tất",stats.done,CheckCircle2]].map(([label,value,Icon]:any)=><div key={label} className="rounded-xl border bg-white p-5 shadow-sm"><Icon className="text-blue-600" size={20}/><p className="mt-4 text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p></div>)}</div>
 <div className="grid min-h-[620px] overflow-hidden rounded-xl border bg-white shadow-sm lg:grid-cols-[380px_1fr]"><aside className="border-r bg-slate-50/60"><form onSubmit={e=>{e.preventDefault();void load();}} className="border-b p-4"><div className="flex items-center rounded-lg border bg-white px-3"><Search size={17} className="text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Mã ticket, tên, email, chủ đề..." className="w-full px-3 py-2.5 text-sm outline-none"/></div><select value={filter} onChange={e=>setFilter(e.target.value)} className="mt-3 w-full rounded-lg border bg-white px-3 py-2 text-sm"><option value="">Tất cả trạng thái</option>{statuses.map(x=><option key={x} value={x}>{statusNames[x]}</option>)}</select></form><div className="max-h-[540px] overflow-y-auto p-3">{loading?<p className="p-5 text-sm text-slate-500">Đang tải...</p>:items.length===0?<p className="p-5 text-sm text-slate-500">Không có yêu cầu phù hợp.</p>:items.map(x=><button key={x.id} onClick={()=>setSelected(x)} className={`mb-2 w-full rounded-lg border p-4 text-left ${selected?.id===x.id?"border-blue-300 bg-blue-50":"bg-white hover:border-slate-300"}`}><div className="flex justify-between gap-2"><b className="text-sm text-blue-700">{x.ticketCode}</b><span className="text-xs text-slate-400">{new Date(x.createdAt).toLocaleDateString("vi-VN")}</span></div><p className="mt-2 truncate font-semibold">{x.subject}</p><p className="mt-1 truncate text-sm text-slate-500">{x.requesterName} · {statusNames[x.status]}</p></button>)}</div></aside>
 <main className="p-6">{!selected?<div className="flex h-full items-center justify-center text-slate-400">Chọn một yêu cầu để xử lý</div>:<div className="mx-auto max-w-3xl"><div className="flex flex-wrap justify-between gap-4 border-b pb-5"><div><p className="text-sm font-bold text-blue-700">{selected.ticketCode}</p><h2 className="mt-1 text-2xl font-bold">{selected.subject}</h2><p className="mt-2 text-sm text-slate-500">{selected.requesterName} · {selected.requesterEmail}</p></div><span className="h-fit rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{selected.category}</span></div><div className="my-6 rounded-xl bg-slate-50 p-5 text-sm leading-7 text-slate-700 whitespace-pre-wrap">{selected.message}</div><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold uppercase text-slate-500">Trạng thái<select disabled={saving} value={selected.status} onChange={e=>void save({status:e.target.value as SupportTicketStatus})} className="mt-2 w-full rounded-lg border px-3 py-2.5 text-sm normal-case text-slate-800">{statuses.map(x=><option key={x} value={x}>{statusNames[x]}</option>)}</select></label><label className="text-xs font-bold uppercase text-slate-500">Ưu tiên<select disabled={saving} value={selected.priority} onChange={e=>void save({priority:e.target.value as SupportTicketPriority})} className="mt-2 w-full rounded-lg border px-3 py-2.5 text-sm normal-case text-slate-800">{priorities.map(x=><option key={x} value={x}>{priorityNames[x]}</option>)}</select></label></div><label className="mt-5 block text-xs font-bold uppercase text-slate-500">Phản hồi / ghi chú xử lý<textarea defaultValue={selected.staffNote??""} key={selected.id+selected.updatedAt} id="staff-note" rows={6} className="mt-2 w-full rounded-xl border p-4 text-sm normal-case outline-none focus:ring-2 focus:ring-blue-100" placeholder="Nhập nội dung phản hồi, hướng xử lý hoặc thông tin cần khách bổ sung..."/></label><button disabled={saving} onClick={()=>void save({staffNote:(document.getElementById("staff-note") as HTMLTextAreaElement)?.value,status:selected.status==="OPEN"?"IN_PROGRESS":selected.status})} className="mt-4 flex items-center gap-2 rounded-lg bg-blue-700 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50"><UserRoundCheck size={17}/>{saving?"Đang lưu...":"Lưu xử lý"}</button>{selected.assignedTo&&<p className="mt-3 text-xs text-slate-400">Phụ trách: {selected.assignedTo}</p>}</div>}</main></div></div>;
};
export default SupportConsolePage;
