import { FormEvent, useState } from "react";
import { ArrowRight, ArrowUp, ExternalLink as Youtube, Globe as Facebook, Mail, MapPin, Phone, Share2 as Instagram, ShieldCheck } from "lucide-react";
import { Link, useLocation } from "react-router-dom";
import { useAuth } from "@ebike/shared-code/hooks";

const linkClass="text-sm text-white/60 transition hover:text-fuchsia-300";
export default function FooterPremium(){
 const location=useLocation();const {isAuthenticated}=useAuth();const [email,setEmail]=useState("");const [notice,setNotice]=useState("");
 if(location.pathname.startsWith("/checkout")||location.pathname.startsWith("/chatbot")||location.pathname==="/messages")return null;
 const subscribe=(e:FormEvent)=>{e.preventDefault();const value=email.trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)){setNotice("Vui lòng nhập email hợp lệ.");return;}const saved=JSON.parse(localStorage.getItem("motionx-newsletter")||"[]") as string[];localStorage.setItem("motionx-newsletter",JSON.stringify([...new Set([...saved,value])]));setEmail("");setNotice("Đăng ký thành công! Ưu đãi mới sẽ được gửi tới bạn.");};
 return <footer className="relative mt-auto overflow-hidden bg-[#0c1511] text-white"><div className="pointer-events-none absolute right-0 top-0 h-96 w-96 rounded-full bg-violet-700/20 blur-[100px]"/><div className="mx-auto max-w-7xl px-6 py-14 md:px-10"><section className="relative mb-14 grid gap-8 rounded-[28px] border border-white/10 bg-white/[.055] p-7 lg:grid-cols-[1fr_.9fr] lg:items-center lg:p-9"><div><span className="text-xs font-bold uppercase tracking-[.24em] text-fuchsia-400">MotionX Insider</span><h2 className="mt-3 text-2xl font-black md:text-3xl">Xe mới, giá tốt và kinh nghiệm mua bán an toàn</h2><p className="mt-2 max-w-xl text-sm leading-6 text-white/55">Nhận bản tin chọn lọc, không spam. Bạn có thể hủy đăng ký bất cứ lúc nào.</p></div><form onSubmit={subscribe}><div className="flex rounded-2xl bg-white p-1.5 text-slate-900"><Mail className="ml-3 self-center text-violet-600" size={19}/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} aria-label="Email nhận bản tin" placeholder="Email của bạn" className="min-w-0 flex-1 px-3 py-2.5 outline-none"/><button className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-violet-700 to-fuchsia-500 px-4 py-2.5 text-sm font-bold text-white">Đăng ký<ArrowRight size={16}/></button></div>{notice&&<p className={`mt-2 text-xs ${notice.startsWith("Đăng")?"text-emerald-300":"text-amber-300"}`}>{notice}</p>}</form></section>
 <section className="grid gap-10 border-b border-white/10 pb-12 sm:grid-cols-2 lg:grid-cols-[1.35fr_.75fr_.75fr_1fr]"><div><Link to="/" className="inline-flex items-center gap-3 text-2xl font-black"><span className="grid h-11 w-11 place-items-center rounded-full bg-gradient-to-br from-violet-600 to-fuchsia-500">M</span>MOTIONX</Link><p className="mt-5 max-w-sm text-sm leading-7 text-white/55">Marketplace mua bán và trao đổi phương tiện tích hợp AI, giúp kết nối minh bạch và giao dịch an toàn hơn.</p><div className="mt-6 flex gap-2"><a href="https://facebook.com" target="_blank" rel="noreferrer" aria-label="Facebook" className="rounded-full border border-white/10 p-3 text-white/60 hover:border-violet-400 hover:text-violet-300"><Facebook size={18}/></a><a href="https://instagram.com" target="_blank" rel="noreferrer" aria-label="Instagram" className="rounded-full border border-white/10 p-3 text-white/60 hover:text-fuchsia-300"><Instagram size={18}/></a><a href="https://youtube.com" target="_blank" rel="noreferrer" aria-label="YouTube" className="rounded-full border border-white/10 p-3 text-white/60 hover:text-red-300"><Youtube size={18}/></a></div></div>
 <div><h3 className="mb-5 text-xs font-black uppercase tracking-[.22em] text-fuchsia-400">Khám phá</h3><nav className="flex flex-col gap-3"><Link className={linkClass} to="/products">Khám phá xe</Link><Link className={linkClass} to="/sell">Đăng tin bán xe</Link><Link className={linkClass} to="/deals">Giao dịch</Link><Link className={linkClass} to="/compare">So sánh xe</Link><Link className={linkClass} to="/chatbot">Tư vấn AI</Link>{isAuthenticated&&<Link className={linkClass} to="/favorites">Xe yêu thích</Link>}</nav></div>
 <div><h3 className="mb-5 text-xs font-black uppercase tracking-[.22em] text-fuchsia-400">Dịch vụ</h3><nav className="flex flex-col gap-3"><Link className={linkClass} to="/support">Trung tâm hỗ trợ</Link><Link className={linkClass} to={isAuthenticated?"/customer/orders":"/auth"}>Theo dõi đơn hàng</Link><Link className={linkClass} to={isAuthenticated?"/customer/profile":"/auth"}>Tài khoản</Link><Link className={linkClass} to="/info/safety">Giao dịch an toàn</Link><Link className={linkClass} to="/info/shipping">Giao nhận & bảo hành</Link></nav></div>
 <div><h3 className="mb-5 text-xs font-black uppercase tracking-[.22em] text-fuchsia-400">Liên hệ</h3><div className="space-y-4 text-sm text-white/60"><a href="tel:19001234" className="flex gap-3 hover:text-white"><Phone size={18} className="shrink-0 text-fuchsia-400"/><span><b className="block text-white">1900 1234</b>08:00 – 20:00 mỗi ngày</span></a><a href="mailto:support@motionx.vn" className="flex gap-3 hover:text-white"><Mail size={18} className="shrink-0 text-fuchsia-400"/><span>support@motionx.vn</span></a><a href="https://maps.google.com/?q=Ho+Chi+Minh+City+Vietnam" target="_blank" rel="noreferrer" className="flex gap-3 hover:text-white"><MapPin size={18} className="shrink-0 text-fuchsia-400"/><span>TP. Hồ Chí Minh, Việt Nam</span></a></div></div></section>
 <div className="flex flex-col gap-5 pt-7 text-xs text-white/40 md:flex-row md:items-center md:justify-between"><p>© {new Date().getFullYear()} MOTIONX. Bảo lưu mọi quyền.</p><nav className="flex flex-wrap gap-x-6 gap-y-2"><Link to="/info/about" className="hover:text-white">Về MOTIONX</Link><Link to="/info/privacy" className="hover:text-white">Chính sách bảo mật</Link><Link to="/info/terms" className="hover:text-white">Điều khoản dịch vụ</Link><span className="flex items-center gap-1"><ShieldCheck size={14}/>Kết nối được bảo vệ</span><button onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} className="flex items-center gap-1 hover:text-white">Lên đầu trang<ArrowUp size={14}/></button></nav></div></div></footer>;
}
