WITH specs(slug,brand,vtype,btype,capacity,speed,range_km,power,brake,drive,warranty) AS (VALUES
('vinfast-evo200-lite','VinFast','E_MOTORBIKE','LFP',22,49,160,1500,'CBS','HUB_MOTOR',36),('vinfast-feliz-s','VinFast','E_MOTORBIKE','LFP',35,78,198,3000,'CBS','HUB_MOTOR',36),('dat-bike-weaver-200','Dat Bike','E_MOTORBIKE','LITHIUM_ION',68,90,200,6000,'DISC','CHAIN',36),('yadea-orla','Yadea','E_MOTORBIKE','LEAD_ACID',22,50,80,1200,'DISC','HUB_MOTOR',24),('yadea-voltguard-p','Yadea','E_MOTORBIKE','LITHIUM_ION',30,65,120,2500,'CBS','HUB_MOTOR',36),('pega-aura-s-plus','Pega','E_MOTORBIKE','LEAD_ACID',22,50,90,1500,'DISC','HUB_MOTOR',24),('giant-explore-e-plus-2','Giant','E_BIKE','LITHIUM_ION',16,25,140,500,'DISC','MID_DRIVE',24),('himo-z20','Himo','E_BIKE','LITHIUM_ION',10,25,80,350,'DISC','HUB_MOTOR',18),('aima-orla-g5','Aima','E_BIKE','LITHIUM_ION',12,35,75,500,'DRUM','HUB_MOTOR',18),('dk-bike-samurai','DK Bike','E_BIKE','LEAD_ACID',20,40,70,800,'DISC','HUB_MOTOR',18),('xiaomi-scooter-4-ultra','Xiaomi','E_SCOOTER','LITHIUM_ION',12,25,70,940,'DISC','HUB_MOTOR',18),('segway-ninebot-max-g2','Segway','E_SCOOTER','LITHIUM_ION',15.3,35,70,1000,'DRUM','HUB_MOTOR',24),('niu-kqi3-pro','NIU','E_SCOOTER','LITHIUM_ION',10.4,32,50,700,'DISC','HUB_MOTOR',18),('yadea-ks5-pro','Yadea','E_SCOOTER','LITHIUM_ION',10.4,30,45,700,'DISC','HUB_MOTOR',18),('pin-lfp-motionx-72v-30ah','MotionX','BATTERY','LFP',30,0,0,0,'DISC','HUB_MOTOR',36),('pin-lithium-motionx-48v-20ah','MotionX','BATTERY','LITHIUM_ION',20,0,0,0,'DISC','HUB_MOTOR',24),('sac-nhanh-motionx-72v-10a','MotionX','ACCESSORY','LITHIUM_ION',0,0,0,720,'DISC','HUB_MOTOR',18),('mu-bao-hiem-thong-minh-mx-halo','MotionX','ACCESSORY','LITHIUM_ION',2,0,0,0,'DISC','HUB_MOTOR',12),('khoa-gps-mx-secure','MotionX','ACCESSORY','LITHIUM_ION',1,0,0,0,'DISC','HUB_MOTOR',12),('thung-sau-mx-box-35l','MotionX','ACCESSORY','LITHIUM_ION',0,0,0,0,'DISC','HUB_MOTOR',12)
)
INSERT INTO ebike_product.product_specifications(product_id,model_code,brand,vehicle_type,battery_type,battery_capacity_ah,max_speed_kmh,max_range_km,motor_power_watts,brake_type,drive_type,warranty_months,smart_features)
SELECT p.id,upper(replace(substring(s.slug,1,18),'-','')),s.brand,s.vtype,s.btype,s.capacity,s.speed,s.range_km,s.power,s.brake,s.drive,s.warranty,'Ứng dụng quản lý, chống trộm và chẩn đoán thông minh' FROM specs s JOIN ebike_product.products p ON p.slug=s.slug
ON CONFLICT(product_id) DO UPDATE SET brand=EXCLUDED.brand,vehicle_type=EXCLUDED.vehicle_type,battery_type=EXCLUDED.battery_type,battery_capacity_ah=EXCLUDED.battery_capacity_ah,max_speed_kmh=EXCLUDED.max_speed_kmh,max_range_km=EXCLUDED.max_range_km,motor_power_watts=EXCLUDED.motor_power_watts,warranty_months=EXCLUDED.warranty_months;

INSERT INTO ebike_product.product_variants(product_id,sku,variant_name,color_name,color_hex,battery_capacity_ah,additional_price,stock_quantity,is_default,is_active)
SELECT p.id,upper('MX-'||substring(md5(p.slug||v.color),1,10)),v.color||' tiêu chuẩn',v.color,v.hex,s.battery_capacity_ah,v.extra,GREATEST(2,p.stock_quantity/3),v.ord=1,true FROM ebike_product.products p JOIN ebike_product.product_specifications s ON s.product_id=p.id CROSS JOIN (VALUES ('Đen nhám','#171717',0,1),('Trắng ngọc','#f5f5f4',300000,2),('Tím Aurora','#7c3aed',500000,3)) v(color,hex,extra,ord) WHERE s.vehicle_type IN ('E_MOTORBIKE','E_BIKE','E_SCOOTER')
ON CONFLICT(sku) DO UPDATE SET stock_quantity=EXCLUDED.stock_quantity,is_active=true;
