import { useEffect, useState } from "react";
import { apiClient } from "@ebike/shared-code/api";
type Entry={id:number;name:string;slug:string;active:boolean;brand_id?:number;category_id?:number};
const empty={name:"",slug:"",active:true,brandId:"",categoryId:""};
export default function AdminVehicleCatalogPage(){
 const [kind,setKind]=useState("categories"),[rows,setRows]=useState<Entry[]>([]),[brands,setBrands]=useState<Entry[]>([]),[categories,setCategories]=useState<Entry[]>([]);
 const [form,setForm]=useState<typeof empty & {id?:number}|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
 const load=async()=>{setLoading(true);setError("");try{const [r,b,c]=await Promise.all([apiClient.get("/admin/vehicle-catalog/"+kind),apiClient.get("/admin/vehicle-catalog/brands"),apiClient.get("/admin/vehicle-catalog/categories")]);setRows(r.data);setBrands(b.data);setCategories(c.data);}catch(e:any){setError(e?.response?.data?.message||e.message);}finally{setLoading(false);}};
 useEffect(()=>{setForm(null);void load();},[kind]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!form)return;setBusy(true);try{await apiClient.post("/admin/vehicle-catalog/"+kind,{...form,brandId:form.brandId?Number(form.brandId):null,categoryId:form.categoryId?Number(form.categoryId):null});setForm(null);await load();}catch(e:any){setError(e?.response?.data?.message||"Không thể lưu. Kiểm tra mã hoặc tên bị trùng.");}finally{setBusy(false);}};
 const cls="rounded-xl border bg-white px-4 py-2 text-sm";
 return <div className="space-y-5"><h2 className="text-2xl font-bold">Danh mục phương tiện</h2><p className="text-sm text-slate-500">Quản lý loại xe, hãng và dòng xe. Ngừng sử dụng để giữ liên kết với tin đăng cũ.</p><div className="flex flex-wrap gap-2">{[["categories","Loại phương tiện"],["brands","Hãng xe"],["models","Dòng xe"]].map(([key,label])=><button key={key} onClick={()=>setKind(key)} className={cls+(kind===key?" text-violet-700 ring-1 ring-violet-300":"")}>{label}</button>)}<button onClick={()=>{setForm(empty);setError("");}} className={cls}>Thêm mới</button></div>{error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{form&&<form onSubmit={save} className="space-y-3 rounded-2xl border bg-white p-5"><h3 className="font-bold">{form.id?"Chỉnh sửa":"Thêm danh mục"}</h3><label className="block text-sm">Tên<input required maxLength={120} className={cls+" mt-1 block w-full"} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="block text-sm">Mã (chữ thường, số và dấu gạch ngang)<input required maxLength={140} pattern="[a-z0-9]+(-[a-z0-9]+)*" className={cls+" mt-1 block w-full"} value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label>{kind==="models"&&<>{[["brandId","Hãng",brands],["categoryId","Loại xe",categories]].map(([key,label,list]:any)=><label key={key} className="block text-sm">{label}<select required className={cls+" mt-1 block w-full"} value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})}><option value="">Chọn...</option>{list.filter((r:Entry)=>r.active).map((r:Entry)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>)}</>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Đang sử dụng</label><div className="flex gap-2"><button disabled={busy} className={cls+" text-violet-700"}>{busy?"Đang lưu...":"Lưu"}</button><button type="button" onClick={()=>setForm(null)} className={cls}>Hủy</button></div></form>}{loading?<p>Đang tải...</p>:<div className="grid gap-3 sm:grid-cols-2">{rows.map(r=><article key={r.id} className="flex items-center justify-between gap-3 rounded-xl border bg-white p-4"><div><b>{r.name}</b><p className="text-xs text-slate-500">{r.slug} · {r.active?"Đang sử dụng":"Ngừng sử dụng"}</p></div><button className={cls} onClick={()=>setForm({id:r.id,name:r.name,slug:r.slug,active:r.active,brandId:String(r.brand_id||""),categoryId:String(r.category_id||"")})}>Sửa</button></article>)}</div>}</div>;
}
