import { useEffect, useState } from "react";
import { adminAPI } from "@ebike/shared-code/api";
import { useAuth } from "@ebike/shared-code/hooks";
import type { AdminAccount, AdminAuditLog } from "@ebike/shared-code/types";

const roles: Record<string,string>={ADMIN:"Quản trị hệ thống",MANAGER:"Quản lý vận hành",CUSTOMER:"Người dùng",OPERATOR:"Nhân sự cũ · Operator",SUPPORT:"Nhân sự cũ · Support",MAINTENANCE:"Nhân sự cũ · Maintenance"};
const statuses: Record<string,string>={ACTIVE:"Hoạt động",LOCKED:"Đã khóa",INACTIVE:"Ngừng hoạt động"};
const input="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm";
const button="rounded-xl border border-violet-200 px-4 py-2 text-sm font-semibold text-violet-700 disabled:opacity-40";
export default function AdminAccountsAccessPage() {
 const {user}=useAuth();
 const [accounts,setAccounts]=useState<AdminAccount[]>([]),[logs,setLogs]=useState<AdminAuditLog[]>([]);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const [tab,setTab]=useState("accounts"),[query,setQuery]=useState(""),[filter,setFilter]=useState("");
 const [creating,setCreating]=useState(false);
 const [form,setForm]=useState({name:"",username:"",email:"",password:"",role:"MANAGER" as AdminAccount["role"]});
 const [change,setChange]=useState<{account:AdminAccount;kind:"role"|"status";value:string}|null>(null);
 const load=async()=>{setLoading(true);try{const [a,l]=await Promise.all([adminAPI.getAccounts(),adminAPI.getAuditLogs()]);setAccounts(a);setLogs(l);setError("");}catch(e:any){setError(e?.response?.data?.message||e.message);}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const save=async(e:React.FormEvent)=>{
  e.preventDefault();setBusy(true);setError("");setSuccess("");
  try {
   if(change){if(change.kind==="role")await adminAPI.updateAccountRole(change.account.id,change.value as AdminAccount["role"]);else await adminAPI.updateAccountStatus(change.account.id,change.value as AdminAccount["status"]);setChange(null);}
   else{await adminAPI.createAccount({...form,status:"ACTIVE",verified:false});setCreating(false);setForm({name:"",username:"",email:"",password:"",role:"MANAGER"});}
   setSuccess("Đã lưu thay đổi và nhật ký trên hệ thống.");await load();
  }catch(cause:any){setError(cause?.response?.data?.message||cause.message||"Không thể lưu.");}finally{setBusy(false);}
 };
 const visible=accounts.filter(a=>(!filter||a.roles.includes(filter))&&[a.name,a.username,a.email].join(" ").toLowerCase().includes(query.toLowerCase()));
 return <div className="space-y-5">
  <header className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-bold">Tài khoản & phân quyền</h2><p className="mt-2 text-sm text-slate-500">Admin quản trị hệ thống. Manager vận hành tin đăng, báo cáo và giao dịch.</p></div><div className="flex gap-2"><button disabled={loading} onClick={()=>void load()} className={button}>Làm mới</button><button onClick={()=>{setCreating(true);setError("");}} className={button}>Tạo tài khoản</button></div></header>
  {error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{success&&<p role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-700">{success}</p>}
  <nav className="flex gap-2">{[["accounts","Tài khoản"],["roles","Phạm vi quyền"],["audit","Nhật ký hệ thống"]].map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={button+(tab===key?" bg-violet-100":" bg-white")}>{label}</button>)}</nav>
  {tab==="accounts"?<><div className="flex flex-wrap gap-3"><input aria-label="Tìm tài khoản" className={input+" flex-1"} placeholder="Tên, email, tên đăng nhập..." value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Lọc vai trò" className={input} value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Tất cả vai trò</option>{Object.entries(roles).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>
  {loading?<p>Đang tải...</p>:<div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr>{["Tài khoản","Vai trò","Trạng thái","Thao tác"].map(h=><th key={h} className="p-4">{h}</th>)}</tr></thead><tbody>{visible.map(a=><tr key={a.id} className="border-t"><td className="p-4"><b>{a.name}</b><p className="text-slate-500">{a.email}</p><p className="text-xs text-slate-400">{a.username}</p></td><td className="p-4">{a.roles.map(r=>roles[r]||r).join(", ")}</td><td className="p-4">{statuses[a.status]}</td><td className="p-4">{String(a.id)===String(user?.id)?<span className="text-xs text-slate-400">Tài khoản đang sử dụng</span>:<div className="flex flex-wrap gap-2"><button className={button} onClick={()=>{setChange({account:a,kind:"role",value:a.role});setError("");}}>Đổi vai trò</button><button className={button} onClick={()=>{setChange({account:a,kind:"status",value:a.status==="ACTIVE"?"LOCKED":"ACTIVE"});setError("");}}>{a.status==="ACTIVE"?"Khóa":"Kích hoạt"}</button>{a.status!=="INACTIVE"&&<button className={button} onClick={()=>{setChange({account:a,kind:"status",value:"INACTIVE"});setError("");}}>Ngừng hoạt động</button>}</div>}</td></tr>)}</tbody></table>{!visible.length&&<p className="p-8 text-center text-slate-500">Không có tài khoản phù hợp.</p>}</div>}</>:tab==="audit"?<div className="space-y-3"><p className="text-sm text-slate-500">100 thao tác gần nhất được ghi nhận tại server.</p>{logs.map(log=><article key={log.id} className="rounded-xl border bg-white p-4"><b>{log.actor}</b> · {log.action}<p className="mt-1 break-words text-sm text-slate-600">{log.target}</p><p className="mt-2 text-xs text-slate-400">{new Date(log.createdAt).toLocaleString("vi-VN")}</p></article>)}</div>:<div className="space-y-4">{[["Người dùng","Đăng, sửa, gửi duyệt và gỡ tin của mình; mua xe, trao đổi với người bán và theo dõi giao dịch cá nhân."],["Manager","Kiểm duyệt tin của người khác, xử lý báo cáo, xem giao dịch, mở tranh chấp và hỗ trợ khách hàng. Không quản lý quyền hoặc xác nhận tiền thay các bên."],["Admin","Có quyền vận hành như manager, thêm quản lý tài khoản, phân quyền, danh mục, biểu phí và nhật ký hệ thống. Không tự duyệt tin của mình." ]].map(([title,description])=><article key={title} className="rounded-2xl border bg-white p-5"><h3 className="font-bold text-violet-700">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p></article>)}</div>}
  {(creating||change)&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={save} role="dialog" aria-modal="true" aria-labelledby="account-form-title" className="max-h-[90vh] w-full max-w-lg space-y-4 overflow-auto rounded-2xl bg-white p-6"><h3 id="account-form-title" className="text-xl font-bold">{change?"Cập nhật tài khoản":"Tạo tài khoản"}</h3>{change?<><p>{change.account.name} · {change.account.email}</p>{change.kind==="role"?<label className="block text-sm">Vai trò mới<select className={input+" mt-2 w-full"} value={change.value} onChange={e=>setChange({...change,value:e.target.value})}>{Object.entries(roles).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>:<p className="text-sm">Chuyển trạng thái thành: <b>{statuses[change.value]}</b>. Lịch sử tin đăng và giao dịch được giữ lại.</p>}</>:<>{(["name","username","email","password"] as const).map((key,index)=><label key={key} className="block text-sm">{["Họ tên","Tên đăng nhập","Email","Mật khẩu ban đầu"][index]}<input required autoComplete={key==="password"?"new-password":"off"} minLength={key==="password"?8:undefined} type={key==="password"?"password":key==="email"?"email":"text"} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className={input+" mt-1 w-full"}/></label>)}<label className="block text-sm">Vai trò<select className={input+" mt-1 w-full"} value={form.role} onChange={e=>setForm({...form,role:e.target.value as AdminAccount["role"]})}>{["CUSTOMER","MANAGER","ADMIN"].map(key=><option key={key} value={key}>{roles[key]}</option>)}</select></label></>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button disabled={busy} type="button" className={button} onClick={()=>{setCreating(false);setChange(null);}}>Hủy</button><button disabled={busy} className="rounded-xl bg-violet-600 px-5 py-2 font-bold text-white disabled:opacity-40">{busy?"Đang lưu...":"Xác nhận"}</button></div></form></div>}
 </div>;
}
